src/Entity/Mark.php
<?php

namespace App\Entity;

use App\Repository\MarkRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MarkRepository::class)]
class Mark
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Student::class, inversedBy: 'marks')]
    private $student;

    #[ORM\Column(type: 'float')]
    private $assignment_1;

    #[ORM\Column(type: 'float')]
    private $assignment_2;

    #[ORM\ManyToOne(targetEntity: Semester::class, inversedBy: 'marks')]
    private $semester;

   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStudent(): ?Student
    {
        return $this->student;
    }

    public function setStudent(?Student $student): self
    {
        $this->student = $student;

        return $this;
    }

    public function getAssignment1(): ?float
    {
        return $this->assignment_1;
    }

    public function setAssignment1(float $assignment_1): self
    {
        $this->assignment_1 = $assignment_1;

        return $this;
    }

    public function getAssignment2(): ?float
    {
        return $this->assignment_2;
    }

    public function setAssignment2(float $assignment_2): self
    {
        $this->assignment_2 = $assignment_2;

        return $this;
    }

    public function getSemester(): ?Semester
    {
        return $this->semester;
    }

    public function setSemester(?Semester $semester): self
    {
        $this->semester = $semester;

        return $this;
    }

    
}

src/Entity/Semester.php
<?php

namespace App\Entity;

use App\Repository\SemesterRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SemesterRepository::class)]
class Semester
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'date')]
    private $date_start;

    #[ORM\Column(type: 'date')]
    private $date_end;

    #[ORM\OneToMany(mappedBy: 'semester', targetEntity: Mark::class)]
    private $marks;


    public function __construct()
    {
        $this->marks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    /**
     * @return Collection<int, Mark>
     */
    public function getMarks(): Collection
    {
        return $this->marks;
    }

    public function addMark(Mark $mark): self
    {
        if (!$this->marks->contains($mark)) {
            $this->marks[] = $mark;
            $mark->setSemester($this);
        }

        return $this;
    }

    public function removeMark(Mark $mark): self
    {
        if ($this->marks->removeElement($mark)) {
            // set the owning side to null (unless already changed)
            if ($mark->getSemester() === $this) {
                $mark->setSemester(null);
            }
        }

        return $this;
    }

   
}

src/Form/SemesterType.php
<?php

namespace App\Form;

use App\Entity\Semester;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class SemesterType extends AbstractType
{
     public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class,
            [
                'label' => 'Semester',
                'required' => true,
                

            ])
            ->add('dateStart', DateType::class, [
                'label'=>'Published date',
                'required' => true,
                'widget' => 'single_text',
            ])
            ->add('dateEnd', DateType::class, [
                
                'label'=>'Published date',
                'required' => true,
                'widget' => 'single_text'  ,
                //Set the dateEnd to be greater than the dateStart
            ])
            ->add('Save', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/SemesterController.php
<?php

namespace App\Controller;

use App\Entity\Semester;
use App\Form\SemesterType;
use App\Repository\SemesterRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
#[Route('/semester')]
class SemesterController extends AbstractController
{
    #[Route('/', name: 'semester_index')]
    public function semesterIndex(ManagerRegistry $registry)
    {
        $semesters = $registry->getRepository(Semester::class)->findAll(); 
        return $this->render('semester/index.html.twig', [
            'semesters' => $semesters
        ]);
    }
    #[Route('/detail/{id}', name: 'semester_detail')]
    public function semesterDetail(ManagerRegistry $registry, $id)
    {
        $semester = $registry->getRepository(Semester::class)->find($id);
        if ($semester == null) {
            $this->addFlash('error', 'Semester not found');
            return $this->redirectToRoute('semester_detail');
        }
        return $this->render('semester/detail.html.twig', [
            'semester' => $semester
        ]);
    }
    #[Route('/delete/{id}', name: 'semester_delete')]
    public function semesterDelete(ManagerRegistry $registry, $id){
        $semesters = $registry->getRepository(Semester::class)->find($id);
        $manager = $registry->getManager();
        $manager->remove($semesters);
        $manager->flush();
        $this->addFlash('Success!!', 'Semester is deleted');
        return $this->redirectToRoute('semester_index');
    }
    #[Route('/add', name: 'semester_add')]
    public function semesterAdd(Request $request, ManagerRegistry $registry){
        $semester = new Semester();
        $form = $this->createForm(SemesterType::class, $semester);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $manager = $registry->getManager();
            $manager -> persist($semester);
            $manager -> flush();
            $this->addFlash('Success', 'Add semester successfull !!');
            return $this->redirectToRoute("semester_index");
        }
        return $this->renderForm('semester/add.html.twig',
                                [
                                    'semesterForm' => $form
                                ]);

    }
    #[Route('edit/{id}', name: 'semester_edit')]
    public function semesterEdit(Request $request ,ManagerRegistry $registry, $id){
        $semester = $registry->getRepository(Semester::class)->find($id);
        $form = $this->createForm(SemesterType::class, $semester);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $manager = $registry->getManager();
            $manager -> persist($semester);
            $manager -> flush();
            $this->addFlash('Success', 'Add semester successfull !!');
            return $this->redirectToRoute("semester_index");
        }
        return $this->renderForm('semester/edit.html.twig',
                                [
                                    'semesterForm' => $form
                                ]);

    }
//     #[Route('/asc', name:'semester_asc')]
//     public function sortAsc(ManagerRegistry $registry, SemesterRepository $semesterRepository){
//     $semesters = $semesterRepository->sortSemesterAsc();
//     return $this->render("semester/index.html.twig",[
//        'semesters' => $semesters 
//     ]);
// }
//      #[Route('/desc', name:'semester_desc')]
//     public function sortDesc(ManagerRegistry $registry, SemesterRepository $semesterRepository){
//     $semesters = $semesterRepository->sortSemesterDesc();
//     return $this->render("semester/index.html.twig",[
//        'semesters' => $semesters 
//     ]);
//     }
    // #[Route('/search', name: 'semester_search')]
    // public function search(Request $request ,SemesterRepository $semesterRepository){
    //     $keyword = $request->get('name');
    //     $semesters = $semesterRepository->search($keyword);
    //     return $this->render('semester/index.html.twig', 
    //                         [
    //                             'semesters' => $semesters,
    //                         ]);
    // }
}

templates/semester/add.html.twig
{% form_theme semesterForm 'bootstrap_5_layout.html.twig' %}
{% extends "base.html.twig" %}

{% block body %}
<div class="container col-md-7">
		<h2>Add new Semester</h2>
</div>
		<div class="container col-md-2 text-center">
		{{ form_start(semesterForm) }}
		{{ form_end(semesterForm) }}
		</div>
{% endblock %}

templates/semester/detail.html.twig
{% extends "base.html.twig" %}
{% block body %}
	<div class="container-fluid col-md-5 text-center">
		<table class="table table-bordered border-primary">
			<h2 class="text text-primary">{{semester.name}}</h2>
			<tr>
				<th>Student Name</th>
				<th>Subject</th>
				<th>Assignment 1</th>
				<th>Assignment 2</th>
				<th>Average</th>
				<th>Rank</th>

			</tr>
			{% if semester.marks != null %}
				{% for mark in semester.marks %}
					<tr>
						<td>{{mark.student.name}}</td>
						<td>{{mark.subject.name}}</td>
						<td>{{mark.assignment1}}</td>
						<td>{{mark.assignment2}}</td>
						<td>{{(mark.assignment1 + mark.assignment2)/2}}</td>
						<th>

							{% if (mark.assignment1 + mark.assignment2)/2 >= 5 %}
								High Grade
							{% else %}
								Lowest
							{% endif %}


						</th>

						<br>
					{% endfor %}
				{% endif %}
			</tr>
		</table>
	</div>
</div>{% endblock %}

templates/semester/edit.html.twig
{% form_theme semesterForm 'bootstrap_5_layout.html.twig' %}
{% extends "base.html.twig" %}

{% block body %}
	<div class="container col-md-7">
		<h2>Edit Semester</h2>
	</div>
	<div class="container col-md-2 text-center">
		{{ form_start(semesterForm) }}
		{{ form_end(semesterForm) }}
	</div>
{% endblock %}

templates/semester/index.html.twig
{% extends "base.html.twig" %}

{% block body %}
	<div class="container-fluid col-md-10 text-center">
		<h2 class="text text-success">Semester</h2>
		{# <form action="{{path('semester_search')}}" method="post">
							<input type="search" name="name" id="">
							<input type="submit" value="Search">
						</form> #}
		<a class="btn btn-primary mt-5" href="{{path('semester_add')}}">ADD</a>
		<table class="table table-bordered">
			<tr>
				<th>ID
					{#<select onchange="window.location.href=this.value">
						<option>Sort</option>
						<option value="{{path('semester_asc')}}">ASC</option>
						<option value="{{path('semester_desc')}}">DESC</option>
					</select>#}
				</th>
				<th>Semester Name</th>
				<th>Date Start</th>
				<th>Date End</th>
				{# <th>Total dates</th> #}
				<th>Menu</th>
			</tr>
			<script language="JavaScript">
				var num = 1
			</script>
			{% for semester in semesters %}
				<tr>
					<td>
						<script language="JavaScript">
							document.write(num++);
						</script>
					</td>
					<td>
						<a style="text-decoration: none" href="{{path('semester_detail',{'id':semester.id})}}">
							{{semester.name}}
						</a>
					</td>
					<td>{{semester.dateStart | date('d/m/Y')}}


					</td>
					<td>{{semester.dateEnd | date('d/m/Y')}}
					</td>
					{# {% set total = date(semester.dateEnd).diff(date(semester.dateStart)).days %}
										<td>{{total}}</td> #}
					<td>
						<a class="btn  btn-success" href="{{path('semester_edit', {'id': semester.id})}}">Edit</a>
						<a class="btn btn-info" href="{{path('semester_delete',{'id':semester.id})}}" onclick="return confirm('Are you sure?')">Delete</a>
					</td>
				</tr>
			{% endfor %}
		</table>
	</div>
{% endblock %}